.\" $Id: jackpot.man,v 1.0 2019/12/28 20:23:41 lhf Exp $
.TH JACKPOT 1 "28 January 2020"
.SH NAME
jackpot \- A SOCKS5-over-TLS Proxy
.SH SYNOPSIS
\fBjackpot\fP [\fIoptions\fP] [\fIargs\fP]
.SH DESCRIPTION
\fBJackpot\fP is a SOCKS5-over-TLS proxy. It works as same as HTTPS protocol, whom highly secured communications over internet.
.PP
Jackpot is made of two parts, tiny HTTP service and SOCKS5 service. After a connection to server from client has been established. Jackpot server side would switch client into SOCKS5 tunnel only if client sent matched serial (jackpot has been hit). Otherwise, client would float above HTTP level.
.PP
\fBJackpot\fP also support feature of username and password verification in SOCKS5 tunnel.
.SH OPTIONS
.TP
\fB-h\fP
show this help.
.TP
\fB-v\fP
show version info.
.TP
\fB-i\fP \fItip\fP
set ip address to \fItip\fP for TLS-binding.
.TP
\fB-p\fP \fItport\fP
set port number to \fItport\fP for TLS-binding.
.TP
\fB-k\fP \fIprivate_key\fP
set private key to \fIprivate_key\fP for tls.
.TP
\fB-c\fP \fIcertificate\fP
set \fIcertificate\fP file for tls.
.TP
\fB-s\fP \fIserial\fP
set \fIserial\fP string.
.TP
\fB-e\fP \fIpage\fP
set web \fIpage\fP file for HTTP responses.
.TP
\fB-a\fP \fIwip\fP
set ip address of Web server (server endpoint) or SOCKS5 server (client endpoint) to \fIwip\fP.
.TP
\fB-w\fP \fIwport\fP
set port number of Web server (server endpoint) or SOCKS5 server (client endpoint) to \fIwport\fP.
.TP
\fB-t\fP \fItimeout\fP
set \fItimeout\fP.
.TP
\fB-m\fP \fIpidfile\fP
set PID file to \fIpidfile\fP.
.TP
\fB-n\fP \fIcfgfile\fP
set configuration file to \fIcfgfile\fP.
.SH EXAMPLE
If we have a host running on internet, whose adddress is [11.22.33.44], then we setup a server whose TLS-endpoint would listening on port 433, and whose web service would listening on port 80. And private key (\fIkey.pem\fP) and certificate file (\fIcert.pem\fP) all prepared. Also we take the string (\fIhello\fP) as serial. The command should look like this:
.TP
\fIjackpot -i 11.22.33.44 -p 433 -a 11.22.33.44 -w 80 -k key.pem -c cert.pem -s hello\fP
As you can see, we didn't set (\fItimeout\fP). In this case, this server would use default timeout (20 seconds).
.PP
We can do the same function by simplify command like this:
.TP
\fIjackpot -k key.pem -c cert.pem -s hello\fP
If we don't set its ip address and port, it will uses the default values (both ip: 0.0.0.0, tport:443, wport: 80).
.PP
If we want server to have username/password verification, we should add verified users to its configuration file and load from it. Here is a draft of users:
.in +7n
.EX
\fI
[user]
user0=alice:a1s2d3f4
user1=bob:qaaaa@@@33
\fP
.EE
.in
.PP
Then add configuration file to arguments and restart server.
.PP
For client side, we can connect above server in this way:
.TP
\fIjackpot -i 11.22.33.44 -p 433 -a 127.0.0.1 -w 1080 -s hello\fP
You can also simplify command by ignoring all arguments except (\fItip\fP) and (\fIserial\fP).
.SH SEE ALSO
jackpot.conf(5)
.PP
For more details please visit <https://jackpot-proxy.sourceforge.net/>.
.SH AUTHOR
Originally written by Hsiang Chen <a.chenxiang.z@gmail.com>.
.\" EOF
